// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: proto/myproto.proto

package myproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VEventType string `protobuf:"bytes,1,opt,name=v_event_type,json=vEventType,proto3" json:"v_event_type,omitempty"`
}

func (x *EventType) Reset() {
	*x = EventType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_myproto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventType) ProtoMessage() {}

func (x *EventType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_myproto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventType.ProtoReflect.Descriptor instead.
func (*EventType) Descriptor() ([]byte, []int) {
	return file_proto_myproto_proto_rawDescGZIP(), []int{0}
}

func (x *EventType) GetVEventType() string {
	if x != nil {
		return x.VEventType
	}
	return ""
}

type BrowsingEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Active          bool       `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Audible         bool       `protobuf:"varint,2,opt,name=audible,proto3" json:"audible,omitempty"`
	AutoDiscardable bool       `protobuf:"varint,3,opt,name=autoDiscardable,proto3" json:"autoDiscardable,omitempty"`
	Discarded       bool       `protobuf:"varint,4,opt,name=discarded,proto3" json:"discarded,omitempty"`
	Duration        float64    `protobuf:"fixed64,5,opt,name=duration,proto3" json:"duration,omitempty"`
	FavIconUrl      string     `protobuf:"bytes,6,opt,name=favIconUrl,proto3" json:"favIconUrl,omitempty"`
	Height          float64    `protobuf:"fixed64,7,opt,name=height,proto3" json:"height,omitempty"`
	Highlighted     bool       `protobuf:"varint,8,opt,name=highlighted,proto3" json:"highlighted,omitempty"`
	Id              int64      `protobuf:"varint,9,opt,name=id,proto3" json:"id,omitempty"`
	Incognito       bool       `protobuf:"varint,10,opt,name=incognito,proto3" json:"incognito,omitempty"`
	Index           int64      `protobuf:"varint,11,opt,name=index,proto3" json:"index,omitempty"`
	OpenerTabId     int64      `protobuf:"varint,12,opt,name=openerTabId,proto3" json:"openerTabId,omitempty"`
	Pinned          bool       `protobuf:"varint,13,opt,name=pinned,proto3" json:"pinned,omitempty"`
	Seccode         string     `protobuf:"bytes,14,opt,name=seccode,proto3" json:"seccode,omitempty"`
	Selected        bool       `protobuf:"varint,15,opt,name=selected,proto3" json:"selected,omitempty"`
	Status          string     `protobuf:"bytes,16,opt,name=status,proto3" json:"status,omitempty"`
	Sub1            string     `protobuf:"bytes,17,opt,name=sub1,proto3" json:"sub1,omitempty"`
	Title           string     `protobuf:"bytes,18,opt,name=title,proto3" json:"title,omitempty"`
	Tld             string     `protobuf:"bytes,19,opt,name=tld,proto3" json:"tld,omitempty"`
	Url             string     `protobuf:"bytes,20,opt,name=url,proto3" json:"url,omitempty"`
	UserId          string     `protobuf:"bytes,21,opt,name=userId,proto3" json:"userId,omitempty"`
	Width           float64    `protobuf:"fixed64,22,opt,name=width,proto3" json:"width,omitempty"`
	WindowId        int64      `protobuf:"varint,23,opt,name=windowId,proto3" json:"windowId,omitempty"`
	MutedInfo       *MutedInfo `protobuf:"bytes,24,opt,name=mutedInfo,proto3" json:"mutedInfo,omitempty"`
	GroupId         int64      `protobuf:"varint,25,opt,name=groupId,proto3" json:"groupId,omitempty"`
	PendingUrl      string     `protobuf:"bytes,26,opt,name=pendingUrl,proto3" json:"pendingUrl,omitempty"`
}

func (x *BrowsingEvent) Reset() {
	*x = BrowsingEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_myproto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrowsingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowsingEvent) ProtoMessage() {}

func (x *BrowsingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_myproto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowsingEvent.ProtoReflect.Descriptor instead.
func (*BrowsingEvent) Descriptor() ([]byte, []int) {
	return file_proto_myproto_proto_rawDescGZIP(), []int{1}
}

func (x *BrowsingEvent) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *BrowsingEvent) GetAudible() bool {
	if x != nil {
		return x.Audible
	}
	return false
}

func (x *BrowsingEvent) GetAutoDiscardable() bool {
	if x != nil {
		return x.AutoDiscardable
	}
	return false
}

func (x *BrowsingEvent) GetDiscarded() bool {
	if x != nil {
		return x.Discarded
	}
	return false
}

func (x *BrowsingEvent) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *BrowsingEvent) GetFavIconUrl() string {
	if x != nil {
		return x.FavIconUrl
	}
	return ""
}

func (x *BrowsingEvent) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BrowsingEvent) GetHighlighted() bool {
	if x != nil {
		return x.Highlighted
	}
	return false
}

func (x *BrowsingEvent) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BrowsingEvent) GetIncognito() bool {
	if x != nil {
		return x.Incognito
	}
	return false
}

func (x *BrowsingEvent) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BrowsingEvent) GetOpenerTabId() int64 {
	if x != nil {
		return x.OpenerTabId
	}
	return 0
}

func (x *BrowsingEvent) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *BrowsingEvent) GetSeccode() string {
	if x != nil {
		return x.Seccode
	}
	return ""
}

func (x *BrowsingEvent) GetSelected() bool {
	if x != nil {
		return x.Selected
	}
	return false
}

func (x *BrowsingEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BrowsingEvent) GetSub1() string {
	if x != nil {
		return x.Sub1
	}
	return ""
}

func (x *BrowsingEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BrowsingEvent) GetTld() string {
	if x != nil {
		return x.Tld
	}
	return ""
}

func (x *BrowsingEvent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BrowsingEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BrowsingEvent) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *BrowsingEvent) GetWindowId() int64 {
	if x != nil {
		return x.WindowId
	}
	return 0
}

func (x *BrowsingEvent) GetMutedInfo() *MutedInfo {
	if x != nil {
		return x.MutedInfo
	}
	return nil
}

func (x *BrowsingEvent) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *BrowsingEvent) GetPendingUrl() string {
	if x != nil {
		return x.PendingUrl
	}
	return ""
}

type MutedInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Muted bool `protobuf:"varint,1,opt,name=muted,proto3" json:"muted,omitempty"`
}

func (x *MutedInfo) Reset() {
	*x = MutedInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_myproto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MutedInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutedInfo) ProtoMessage() {}

func (x *MutedInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_myproto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutedInfo.ProtoReflect.Descriptor instead.
func (*MutedInfo) Descriptor() ([]byte, []int) {
	return file_proto_myproto_proto_rawDescGZIP(), []int{2}
}

func (x *MutedInfo) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

type TargetElement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag   string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Id    string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Class string `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"`
	Type  string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *TargetElement) Reset() {
	*x = TargetElement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_myproto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetElement) ProtoMessage() {}

func (x *TargetElement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_myproto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetElement.ProtoReflect.Descriptor instead.
func (*TargetElement) Descriptor() ([]byte, []int) {
	return file_proto_myproto_proto_rawDescGZIP(), []int{3}
}

func (x *TargetElement) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *TargetElement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TargetElement) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *TargetElement) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ClickEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TabId     uint32         `protobuf:"varint,1,opt,name=tabId,proto3" json:"tabId,omitempty"`
	Timestamp int64          `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Target    *TargetElement `protobuf:"bytes,11,opt,name=target,proto3" json:"target,omitempty"`
	Path      []string       `protobuf:"bytes,12,rep,name=path,proto3" json:"path,omitempty"`
	IsTrusted bool           `protobuf:"varint,13,opt,name=isTrusted,proto3" json:"isTrusted,omitempty"`
	PageUrl   string         `protobuf:"bytes,14,opt,name=pageUrl,proto3" json:"pageUrl,omitempty"`
}

func (x *ClickEvent) Reset() {
	*x = ClickEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_myproto_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClickEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickEvent) ProtoMessage() {}

func (x *ClickEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_myproto_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickEvent.ProtoReflect.Descriptor instead.
func (*ClickEvent) Descriptor() ([]byte, []int) {
	return file_proto_myproto_proto_rawDescGZIP(), []int{4}
}

func (x *ClickEvent) GetTabId() uint32 {
	if x != nil {
		return x.TabId
	}
	return 0
}

func (x *ClickEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ClickEvent) GetTarget() *TargetElement {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ClickEvent) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *ClickEvent) GetIsTrusted() bool {
	if x != nil {
		return x.IsTrusted
	}
	return false
}

func (x *ClickEvent) GetPageUrl() string {
	if x != nil {
		return x.PageUrl
	}
	return ""
}

var File_proto_myproto_proto protoreflect.FileDescriptor

var file_proto_myproto_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x76, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x22, 0xc7, 0x05, 0x0a, 0x0d, 0x42, 0x72, 0x6f, 0x77, 0x73, 0x69, 0x6e,
	0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x75, 0x64, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x61, 0x75, 0x64, 0x69, 0x62, 0x6c, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x61, 0x75, 0x74, 0x6f,
	0x44, 0x69, 0x73, 0x63, 0x61, 0x72, 0x64, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0f, 0x61, 0x75, 0x74, 0x6f, 0x44, 0x69, 0x73, 0x63, 0x61, 0x72, 0x64, 0x61, 0x62,
	0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x73, 0x63, 0x61, 0x72, 0x64, 0x65, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x64, 0x69, 0x73, 0x63, 0x61, 0x72, 0x64, 0x65, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a,
	0x66, 0x61, 0x76, 0x49, 0x63, 0x6f, 0x6e, 0x55, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x66, 0x61, 0x76, 0x49, 0x63, 0x6f, 0x6e, 0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x68, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x68, 0x69, 0x67, 0x68, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x68, 0x69, 0x67, 0x68, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x63, 0x6f, 0x67, 0x6e,
	0x69, 0x74, 0x6f, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x6e, 0x63, 0x6f, 0x67,
	0x6e, 0x69, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x70,
	0x65, 0x6e, 0x65, 0x72, 0x54, 0x61, 0x62, 0x49, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0b, 0x6f, 0x70, 0x65, 0x6e, 0x65, 0x72, 0x54, 0x61, 0x62, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x70, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x70, 0x69,
	0x6e, 0x6e, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x63, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x75, 0x62, 0x31, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x73, 0x75, 0x62, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x74, 0x6c, 0x64, 0x18, 0x13, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x6c, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x15, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74,
	0x68, 0x18, 0x16, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x1a,
	0x0a, 0x08, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x49, 0x64, 0x18, 0x17, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x09, 0x6d, 0x75,
	0x74, 0x65, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x18, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x4d, 0x75, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x6d, 0x75, 0x74, 0x65, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18,
	0x19, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x18, 0x1a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x22, 0x21,
	0x0a, 0x09, 0x4d, 0x75, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x6d,
	0x75, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6d, 0x75, 0x74, 0x65,
	0x64, 0x22, 0x5b, 0x0a, 0x0d, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x45, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x74, 0x61, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xb4,
	0x01, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x61, 0x62, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x61,
	0x62, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x12, 0x26, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1c, 0x0a,
	0x09, 0x69, 0x73, 0x54, 0x72, 0x75, 0x73, 0x74, 0x65, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x69, 0x73, 0x54, 0x72, 0x75, 0x73, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61,
	0x67, 0x65, 0x55, 0x72, 0x6c, 0x42, 0x10, 0x5a, 0x0e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b,
	0x6d, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_myproto_proto_rawDescOnce sync.Once
	file_proto_myproto_proto_rawDescData = file_proto_myproto_proto_rawDesc
)

func file_proto_myproto_proto_rawDescGZIP() []byte {
	file_proto_myproto_proto_rawDescOnce.Do(func() {
		file_proto_myproto_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_myproto_proto_rawDescData)
	})
	return file_proto_myproto_proto_rawDescData
}

var file_proto_myproto_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_myproto_proto_goTypes = []interface{}{
	(*EventType)(nil),     // 0: EventType
	(*BrowsingEvent)(nil), // 1: BrowsingEvent
	(*MutedInfo)(nil),     // 2: MutedInfo
	(*TargetElement)(nil), // 3: TargetElement
	(*ClickEvent)(nil),    // 4: ClickEvent
}
var file_proto_myproto_proto_depIdxs = []int32{
	2, // 0: BrowsingEvent.mutedInfo:type_name -> MutedInfo
	3, // 1: ClickEvent.target:type_name -> TargetElement
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_myproto_proto_init() }
func file_proto_myproto_proto_init() {
	if File_proto_myproto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_myproto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_myproto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrowsingEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_myproto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MutedInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_myproto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TargetElement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_myproto_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClickEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_myproto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_myproto_proto_goTypes,
		DependencyIndexes: file_proto_myproto_proto_depIdxs,
		MessageInfos:      file_proto_myproto_proto_msgTypes,
	}.Build()
	File_proto_myproto_proto = out.File
	file_proto_myproto_proto_rawDesc = nil
	file_proto_myproto_proto_goTypes = nil
	file_proto_myproto_proto_depIdxs = nil
}
